[application]

# App (Project) Name
name = "nandu-web"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
# out_dir = "docs"
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]
# base_path = "https://github.com/Srinanda-Yallapragada/nandu-web"

# HTML title tag content
title = "nandu-web"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style fie

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
